#!/bin/sh
sleep 20
printf "\r" > /dev/nmdm-wifibox.1B
sleep 1
printf "root\r" > /dev/nmdm-wifibox.1B
sleep 1
printf "ip addr flush dev eth0\r" > /dev/nmdm-wifibox.1B
sleep 1
printf "ip addr add 192.168.100.1/24 dev eth0\r" > /dev/nmdm-wifibox.1B
sleep 1
printf "ip link set dev eth0 up\r" > /dev/nmdm-wifibox.1B
sleep 1
printf "iw dev wlan0 set power_save off\r" > /dev/nmdm-wifibox.1B
